options(warn = -1)
library(shiny)
library(shinythemes)
library(shinydashboard)
library(shinycssloaders)
library(shinydisconnect)
library(DT)
library(future.apply)
library(dplyr)
library(tidyr)
library(ggplot2)
library(colourpicker)
library(Cairo)
library(openxlsx)
library(data.table)
library(gtools)
library(writexl)
library(qqman)
library(reshape2)
source("script/mod_gwas_ui.R")
source("script/mod_gwas_server.R")
source("script/readNewData.R")
source("script/gwas_emmax_cov.R")
source("script/extraxt_gene.R")
source("script/manhattan_qq_plot.R")

load("./data/Bna_gene_anno.RData")
footerTagList <- list(
  tags$footer(id = "myFooter",
              shiny::includeHTML("www/md/footer.html")
  )
)
